server:
  port: 9091
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false

#spring:
##  h2:
##    console:
##      enabled: true
#  datasource:
##    url: jdbc:h2:mem:mydb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#    url: jdbc:mysql://localhost:3306/db_example
#    username: shantanu
#    password: Lead@123
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#    hibernate:
#      ddl-auto: update

#  spring.datasource.url=jdbc:mysql://localhost:3306/demo?allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&useSSL=false
#  spring.datasource.username=shantanu
#  spring.datasource.password=shantanu
#  spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
#  spring.jpa.show-sql=true
#  spring.jpa.hibernate.ddl-auto=update
#  #spring.jpa.hibernate.ddl-auto=create-drop
#  spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&useSSL=false
    username: shantanu
    password: shantanu
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

keycloak:
  realm: springboot
  auth-server-url: http://localhost:8080/
  resource: springboot-keycloak
  public-client: true
  bearer-only: true

management:
  endpoints:
    web:
      exposure:
        include: metrics,prometheus

getAllPostsApiUrl: https://blogzen.herokuapp.com/api/posts
weatherStackApiUrl: http://api.weatherstack.com/current?access_key=f216262609602500c30959e57ef04c81&units=s&query=

