server:
  port: 9090

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:mydb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect


keycloak:
  realm: springboot
  auth-server-url: http://localhost:8080/
  resource: springboot-keycloak
  public-client: true
  bearer-only: true



getAllPostsApiUrl: https://blogzen.herokuapp.com/api/posts
weatherStackApiUrl: http://api.weatherstack.com/current?access_key=f216262609602500c30959e57ef04c81&units=s&query=

